"""initial

Revision ID: b2cacd2e7943
Revises:
Create Date: 2026-05-04 23:50:37.544830

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b2cacd2e7943"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "courses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("credits", sa.Integer(), nullable=False),
        sa.Column(
            "category",
            sa.Enum("core", "focus_study", "elective", "general", name="categoryenum"),
            nullable=False,
        ),
        sa.Column("is_cs_elective_eligible", sa.Boolean(), nullable=False),
        sa.Column("prereq_description", sa.String(), nullable=True),
        sa.Column("min_grade_required", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "degree_requirements",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("credits_required", sa.Integer(), nullable=False),
        sa.Column(
            "category_filter",
            sa.Enum("core", "focus_study", "elective", "general", name="categoryenum"),
            nullable=False,
        ),
        sa.Column("notes", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("hashed_password", sa.String(), nullable=False),
        sa.Column("college", sa.String(), nullable=True),
        sa.Column("major", sa.String(), nullable=True),
        sa.Column("degree_type", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "student_courses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("course_id", sa.Integer(), nullable=False),
        sa.Column("semester", sa.String(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("planned", "in_progress", "completed", name="statusenum"),
            nullable=False,
        ),
        sa.Column("grade", sa.String(), nullable=True),
        sa.Column("grade_points", sa.Float(), nullable=True),
        sa.Column("credits_applied", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["courses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("student_courses")
    op.drop_table("users")
    op.drop_table("degree_requirements")
    op.drop_table("courses")
    # ### end Alembic commands ###
